#include "Report.h"

Report::Report(int id, MyString type, MyString sum, MyString res, int genBy, Date genDate) {
    reportID = id;
    reportType = type;
    summary = sum;
    result = res;
    generatedBy = genBy;
    generatedDate = genDate;
    published = false;
}

void Report::addRelatedEquipment(Equipment* e) {
    relatedEquipment.push_back(e);
}

void Report::generateReport() {
    cout << "----- Report #" << reportID << " (" << reportType << ") -----" << endl;
    cout << "Summary : " << summary << endl;
    cout << "Result  : " << result << endl;
    cout << "Generated by Scientist ID: " << generatedBy << " on " << generatedDate << endl;
    if (!relatedEquipment.isEmpty()) {
        cout << "Equipment referenced: ";
        for (int i = 0; i < relatedEquipment.size(); i++) {
            cout << relatedEquipment[i]->getEquipmentName();
            if (i != relatedEquipment.size() - 1) cout << ", ";
        }
        cout << endl;
    }
}

void Report::publishReport() {
    published = true;
    cout << "Report #" << reportID << " has been published." << endl;
}

int Report::getReportID() const {
    return reportID;
}

MyString Report::getReportType() const {
    return reportType;
}
